version: "3"
services:
  tor:
    build:
      context: ./tor
    expose:
    - 9050
    restart: always
    volumes:
    - ./tor/torrc:/etc/tor/torrc 
  v2ray:
    image: v2ray/official:latest
    expose:
    - "10000"
    restart: always
    depends_on:
    - tor
    volumes:
    - ./v2ray/config.json:/etc/v2ray/config.json
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    - 443:443
    restart: always
    depends_on:
    - v2ray
    volumes:
    - ./nginx/data:/usr/share/nginx/html
    - ./nginx/v2ray.conf:/etc/nginx/conf.d/v2ray.conf
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/server.crt:/etc/nginx/ssl/server.crt
    - ./nginx/server.key:/etc/nginx/ssl/server.key

